### ISSUE TITLE
Moving object can't be seen?

### ISSUE THREAD

**Issue by arvindkyutech** [aistairc/mf-cesium#42]
I have followed the steps according to https://github.com/aistairc/mf-cesium. I am using Cesium-1.69 . To explore data locally, I drag and drop json file present in data folder present inside mf-cesium folder. I can't see moving object. There is some error in demo.html file. ( One error I have corrected as demo.html was  using FileI0.js but file present in folder was Filei0.js just typo), but at present I get following error on clicking the JSON file I have uploaded. I get following error. Can you please help with this situation.

`Uncaught TypeError: Cannot read property '_external' of undefined
    at PrimitiveCollection.add (Cesium.js:1)
    at Stinuum.GeometryViewer.clear (stinuum.js:492)
    at Stinuum.TemporalMap.show (stinuum.js:3643)
    at showTemporalMap (ViewProperties.js:28)
    at HTMLDivElement.<anonymous> (DivListMaker.js:259)`

**Comment by TaehoonK** [comment]
We updated to the new Stinuum version to support [OGC MF-JSON](https://docs.opengeospatial.org/is/19-045r3/19-045r3.html). 
I'm not sure about your MF-JSON format (Best Practice or OGC MF-JSON). 
Please try this version.

**Comment by arvindkyutech** [comment]
Thank You very much, Now it's working.
